name: Release

concurrency:
  group: ${{ github.event.inputs.ref || github.ref }}-workflow-release
  cancel-in-progress: true

on:
  push:
    tags:
      - v*
    branches:
      - 'v*-release'
  release:
    types: [ published ]
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, Tag or Commit SHA'
        required: false
        default: ''
      upload_pypi:
        description: 'Upload to PyPI'
        type: boolean
        required: false
        default: false

env:
  CI: 1
  ref: ${{ github.event.inputs.ref || github.ref }}

permissions:
  contents: read

jobs:
  release:
    name: build release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'repository_dispatch' || github.event.inputs.upload_pypi == 'true'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ env.ref }}

      - name: set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.13"

      - name: Install build tools
        run: |
          pip install uv
          uv pip install build "setuptools>=77.0.1,<83" twine packaging wheel -U --system

      - name: Build package
        run: |
          rm -rf dist build
          python -m build --sdist --wheel --no-isolation

      - name: Test wheel install
        run: |
          uv pip install dist/*.whl --system

      - run: python -c "from transformers import *"

      - name: Install torch extra
        run: |
          uv pip install -e .[torch] --system

      - run: python -c "from transformers import pipeline; classifier = pipeline('text-classification'); assert classifier('What a nice release')[0]['score'] > 0"

      - name: Check package
        run: |
          twine check --strict dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: python-dist
          path: dist/**

      - name: Publish package distributions to PyPI
        if: github.event_name == 'release' || github.event.inputs.upload_pypi == 'true'
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_KEY }}
        run: |
          python -m twine upload dist/*
